name: Main Workflow

on:
  workflow_dispatch: 

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Call reusable Workflow
        uses: ./.github/workflows/mongodb.yml

      - name: Continue with Main Workflow Steps
        run: echo "This is a main workflow step."
