name: Mongodb Service the reusable workflow

on:
  workflow_call:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master
      - develop

defaults:
  run:
    working-directory: ./mongodb

jobs:
  container-job:
    runs-on: ubuntu-latest
    container:
      image: node:18.10

    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: node client.js
        env:
          MONGODB_HOST: mongodb
          MONGODB_PORT: ${{ job.services.mongodb.ports[27017] }}
 
